name: desafio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.0.0 # Mantenha aqui
  mask_text_input_formatter: ^2.0.0
  http: ^1.2.2
  provider: ^6.1.2
  mysql1: ^0.20.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
